management.metrics.export.wavefront:
  api-token: ${WAVEFRONT_API_TOKEN}
  uri: ${WAVEFRONT_URI:https://vmware.wavefront.com}
wavefront.application:
  name: petclinic-microservices-spring-one
  service: ${spring.application.name}
